# Generated by Django 2.2.6 on 2019-10-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20191029_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('bucket', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='version',
        ),
    ]
