# Generated by Django 2.2.6 on 2019-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20191029_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffqueue',
            name='path',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='handoffqueue',
            name='bucket',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
